
language: node_js
node_js:
  - 13
services:
  - docker
  
# Pre-testing installs
install:
  - echo "nothing needs to be installed"
# Scripts to be run such as tests

before_script:
  - echo "no tests"
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  
  - docker tag udagram-api-user bishop02/udagram-api-user:v1
  - docker tag udagram-api-feed bishop02/udagram-api-feed:v1
  - docker tag udagram-frontend bishop02/udagram-frontend:v1
  - docker tag reverseproxy bishop02/udagram-reverseproxy:v1


after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  - docker push bishop02/udagram-api-feed:v1
  - docker push bishop02/udagram-api-user:v1
  - docker push bishop02/udagram-frontend:v1
  - docker push bishop02/reverseproxy:v1
